export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_ASYNC = "ADD_TASK_ASYNC"
export const FETCH_TASK_BY_ID = "FETCH_TASK_BY_ID"
export const EDIT_TASK = "EDIT_TASK"
export const EDIT_TASK_ASYNC = "EDIT_TASK_ASYNC"